name: Release on PyPI

on:
    push:
        tags:
            - v*

jobs:
    pypi-publish:
        name: Upload release to PyPI
        runs-on: ubuntu-latest
        environment:
            name: release
            url: https://pypi.org/p/pakler
        permissions:
            id-token: write
        steps:
          - name: Checkout repo
            uses: actions/checkout@v3
          - name: Set up Python
            uses: actions/setup-python@v4
            with:
                python-version: "3.8"
          - name: Install dependencies
            run: |
                python -m pip install --upgrade pip
                python -m pip install build
          - name: Build package
            run: python -m build
          - name: Upload distributions
            uses: actions/upload-artifact@v3
            with:
                name: dist
                path: dist/*
                if-no-files-found: error
          - name: Publish package distributions to PyPI
            uses: pypa/gh-action-pypi-publish@release/v1
            with:
                print-hash: true